displayName=Detailed Overlay
author=Aiirik
description=Shows item and combat overlays for potions, teleport tablets, staves, and combat styles and max hits
tags=inventory,items,doses,teleport,staff,combat,overlay,information,runes
plugins=com.aiirik.detailedoverlay.DetailedOverlayPlugin
